version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint --disable=E0611,C0303,C0115,C0304,C0114,C0301,C0410,W0611 *.py **/*.py || true
artifacts:
    files:
        - '**/*'